services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=brticketsmono'
      - 'POSTGRES_PASSWORD=tccpresentation'
      - 'POSTGRES_USER=yankdev'
    ports:
      - '5432:5432'
